#!/bin/bash

# JankyBorders https://github.com/FelixKratz/JankyBorders
# Colors       https://catppuccin.com/palette/

options=(
	style=round
	width=3.0
	hidpi=on
	active_color=0x808aadf4 # Catppuccin Macchiato Blue
	inactive_color=0x80939ab7 # Catppuccin Macchiato Overlay 2
)

borders "${options[@]}"
